// code/homepage-react/src/App.jsx
import { useState } from 'react'
import './App.css'

function App() {
  const currentYear = new Date().getFullYear();
  
  // Correct Mirage Studio team data (4 members)
  const teamMembers = [
    {
      id: 'mirage-manager',
      name: 'Mirage Manager',
      role: 'Operations Director',
      description: 'Coordinates team workflows and timelines.',
      expertise: ['Team Coordination', 'Process Optimization'],
      color: '#F59E0B'
    },
    {
      id: 'mirage-researcher',
      name: 'Mirage Researcher',
      role: 'Research AI',
      description: 'Research specialist for Mirage Studio.',
      expertise: ['Market Research', 'Technology Analysis'],
      color: '#10B981'
    },
    {
      id: 'mirage-engineer',
      name: 'Mirage Engineer',
      role: 'Development Specialist',
      description: 'Development and implementation specialist.',
      expertise: ['Full-Stack Development', 'CI/CD'],
      color: '#4F46E5'
    },
    {
      id: 'mirage-assistant',
      name: 'Mirage Assistant',
      role: 'Support & Coordination',
      description: 'Support and coordination specialist.',
      expertise: ['Documentation', 'Team Support'],
      color: '#EC4899'
    }
  ];

  // Only Mirage Studio Website project
  const activeProjects = [
    {
      id: 'mirage-homepage',
      name: 'Mirage Studio Website',
      status: 'Active',
      lead: 'Mirage Manager',
      progress: 95
    }
  ];

  return (
    <main className="max-w-6xl mx-auto px-8">
      {/* Navigation */}
      <nav className="py-6 bg-white border-b border-gray-200 -mx-8 px-8 mb-0">
        <div className="max-w-6xl mx-auto flex justify-between items-center">
          <div className="flex flex-col">
            <span className="text-2xl font-bold text-gray-900">Mirage Studio</span>
            <span className="text-xs text-gray-500">Research Collective</span>
          </div>
          <div className="hidden md:flex gap-8">
            <a href="#about" className="text-gray-500 font-medium no-underline hover:text-indigo-600 transition-colors">About</a>
            <a href="#team" className="text-gray-500 font-medium no-underline hover:text-indigo-600 transition-colors">Team</a>
            <a href="#projects" className="text-gray-500 font-medium no-underline hover:text-indigo-600 transition-colors">Projects</a>
            <a href="#contact" className="text-gray-500 font-medium no-underline hover:text-indigo-600 transition-colors">Contact</a>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="py-16 text-center">
        <div className="max-w-6xl mx-auto">
          <h1 className="text-4xl md:text-5xl font-bold mb-4 text-gray-900 leading-tight">
            Intelligent Research Through
            <span className="text-indigo-600"> Collaborative Expertise</span>
          </h1>
          <p className="text-lg text-gray-500 max-w-2xl mx-auto mb-8">
            A specialized research collective combining methodological rigor with structured teamwork.
          </p>
          <div className="flex justify-center gap-12 mt-8">
            <div className="flex flex-col items-center">
              <div className="text-4xl font-bold text-indigo-600">{teamMembers.length}</div>
              <div className="text-sm text-gray-500">Team Members</div>
            </div>
            <div className="flex flex-col items-center">
              <div className="text-4xl font-bold text-indigo-600">{activeProjects.length}</div>
              <div className="text-sm text-gray-500">Active Projects</div>
            </div>
          </div>
        </div>
      </section>

      {/* Team Structure */}
      <section className="py-16 bg-white -mx-8 px-8" id="team">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-2 text-gray-900">Team Structure</h2>
          <p className="text-center text-gray-500 mb-12">A carefully organized collective of specialists</p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {teamMembers.map(member => (
              <div key={member.id} className="bg-gray-50 rounded-2xl p-8 text-center border border-gray-200">
                <div
                  className="w-20 h-20 rounded-full flex items-center justify-center text-white text-2xl font-semibold mx-auto mb-4"
                  style={{ background: member.color }}
                >
                  {member.name.split(' ').map(n => n[0]).join('')}
                </div>
                <h3 className="text-xl font-semibold mb-1 text-gray-900">{member.name}</h3>
                <div className="text-indigo-600 font-medium mb-4">{member.role}</div>
                <p className="text-gray-500 mb-4">{member.description}</p>
                <div className="flex flex-wrap justify-center gap-2">
                  {member.expertise.map((skill, idx) => (
                    <span key={idx} className="px-3 py-1 bg-indigo-50 border border-indigo-200 rounded-full text-xs text-indigo-600">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Projects */}
      <section className="py-16" id="projects">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-center mb-2 text-gray-900">Active Projects</h2>
          <p className="text-center text-gray-500 mb-12">Current research initiatives</p>
          
          <div className="grid grid-cols-1 md:grid-cols-1 gap-8 max-w-2xl mx-auto">
            {activeProjects.map(project => (
              <div key={project.id} className="bg-white rounded-2xl p-6 border border-gray-200 shadow-sm">
                <div className="flex justify-between items-center mb-4">
                  <span className="px-3 py-1 bg-emerald-500 text-white rounded-full text-xs font-semibold">
                    {project.status}
                  </span>
                  <span className="text-sm text-gray-500">Lead: {project.lead}</span>
                </div>
                <h3 className="text-xl font-semibold mb-4 text-gray-900">{project.name}</h3>
                <div className="h-2 bg-gray-200 rounded-full overflow-hidden mb-2">
                  <div
                    className="h-full bg-indigo-600 rounded-full transition-all duration-300"
                    style={{ width: `${project.progress}%` }}
                  ></div>
                </div>
                <div className="text-sm text-gray-500 text-right">{project.progress}% Complete</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 bg-gray-50 border-t border-gray-200 -mx-8 px-8">
        <div className="max-w-6xl mx-auto px-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div>
              <div className="text-xl font-bold text-gray-900">Mirage Studio</div>
              <p className="text-gray-500 text-sm">Research · Collaboration · Excellence</p>
            </div>
            <div className="text-gray-500 text-sm">
              &copy; {currentYear} Mirage Studio Research Collective
            </div>
          </div>
        </div>
      </footer>
    </main>
  )
}

export default App

// code/homepage-app/src/App.svelte
<script>
  let currentYear = new Date().getFullYear();
  
  // 真实团队数据
  const teamMembers = [
    {
      id: 'creator',
      name: 'Creator',
      role: 'Founder & Director',
      description: 'Visionary leader and project overseer.',
      expertise: ['Strategic Planning', 'Research Direction'],
      color: '#4F46E5'
    },
    {
      id: 'roy-batty',
      name: 'Roy Batty',
      role: 'Lead Researcher',
      description: 'Directs specialized research initiatives.',
      expertise: ['Behavioral Research', 'Data Analysis'],
      color: '#10B981'
    },
    {
      id: 'mirage-manager',
      name: 'Mirage Manager',
      role: 'Operations Director',
      description: 'Coordinates team workflows and timelines.',
      expertise: ['Team Coordination', 'Process Optimization'],
      color: '#F59E0B'
    }
  ];

  const activeProjects = [
    {
      id: 'emma-training',
      name: 'Emma Training Project',
      status: 'Active',
      lead: 'Roy Batty',
      progress: 85
    },
    {
      id: 'mirage-homepage',
      name: 'Mirage Studio Website',
      status: 'Active',
      lead: 'Mirage Manager',
      progress: 90
    }
  ];
</script>

<main>
  <!-- 导航栏 -->
  <nav class="navbar">
    <div class="nav-container">
      <div class="logo">
        <span class="logo-text">Mirage Studio</span>
        <span class="logo-subtitle">Research Collective</span>
      </div>
      <div class="nav-menu">
        <a href="#about" class="nav-link">About</a>
        <a href="#team" class="nav-link">Team</a>
        <a href="#projects" class="nav-link">Projects</a>
        <a href="#contact" class="nav-link">Contact</a>
      </div>
    </div>
  </nav>

  <!-- 主标题区域 -->
  <section class="hero">
    <div class="hero-container">
      <div class="hero-content">
        <h1 class="hero-title">
          Intelligent Research Through
          <span class="accent">Collaborative Expertise</span>
        </h1>
        <p class="hero-description">
          A specialized research collective combining methodological rigor with structured teamwork.
        </p>
        <div class="hero-stats">
          <div class="stat">
            <div class="stat-number">{teamMembers.length}</div>
            <div class="stat-label">Team Members</div>
          </div>
          <div class="stat">
            <div class="stat-number">{activeProjects.length}</div>
            <div class="stat-label">Active Projects</div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- 团队架构 -->
  <section class="team" id="team">
    <div class="section-container">
      <h2 class="section-title">Team Structure</h2>
      <p class="section-subtitle">A carefully organized collective of specialists</p>
      
      <div class="team-grid">
        {#each teamMembers as member}
          <div class="team-card">
            <div class="member-avatar" style="background: {member.color}">
              {member.name.split(' ').map(n => n[0]).join('')}
            </div>
            <h3 class="member-name">{member.name}</h3>
            <div class="member-role">{member.role}</div>
            <p class="member-description">{member.description}</p>
            <div class="member-expertise">
              {#each member.expertise as skill}
                <span class="skill-tag">{skill}</span>
              {/each}
            </div>
          </div>
        {/each}
      </div>
    </div>
  </section>

  <!-- 项目展示 -->
  <section class="projects" id="projects">
    <div class="section-container">
      <h2 class="section-title">Active Projects</h2>
      <p class="section-subtitle">Current research initiatives</p>
      
      <div class="projects-grid">
        {#each activeProjects as project}
          <div class="project-card">
            <div class="project-header">
              <div class="project-status">{project.status}</div>
              <div class="project-lead">Lead: {project.lead}</div>
            </div>
            <h3 class="project-title">{project.name}</h3>
            <div class="progress-bar">
              <div class="progress-fill" style="width: {project.progress}%"></div>
            </div>
            <div class="progress-text">{project.progress}% Complete</div>
          </div>
        {/each}
      </div>
    </div>
  </section>

  <!-- 页脚 -->
  <footer class="footer">
    <div class="footer-container">
      <div class="footer-content">
        <div class="footer-brand">
          <div class="footer-logo">Mirage Studio</div>
          <p class="footer-tagline">Research · Collaboration · Excellence</p>
        </div>
        <div class="copyright">
          &copy; {currentYear} Mirage Studio Research Collective
        </div>
      </div>
    </div>
  </footer>
</main>

<style>
  :global(body) {
    margin: 0;
    padding: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #fafafa;
    color: #1a1a1a;
    line-height: 1.6;
  }

  /* 导航栏 */
  .navbar {
    padding: 1.5rem 2rem;
    background: white;
    border-bottom: 1px solid #e5e5e5;
  }

  .nav-container {
    max-width: 1200px;
    margin: 0 auto;
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .logo {
    display: flex;
    flex-direction: column;
  }

  .logo-text {
    font-size: 1.5rem;
    font-weight: 700;
    color: #1a1a1a;
  }

  .logo-subtitle {
    font-size: 0.75rem;
    color: #666;
  }

  .nav-menu {
    display: flex;
    gap: 2rem;
  }

  .nav-link {
    color: #555;
    text-decoration: none;
    font-weight: 500;
  }

  .nav-link:hover {
    color: #4F46E5;
  }

  /* 主标题区域 */
  main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 2rem;
  }

  .hero {
    padding: 4rem 0;
    text-align: center;
  }

  .hero-title {
    font-size: 2.5rem;
    font-weight: 700;
    margin-bottom: 1rem;
  }

  .accent {
    color: #4F46E5;
  }

  .hero-description {
    font-size: 1.125rem;
    color: #666;
    max-width: 600px;
    margin: 0 auto 2rem;
  }

  .hero-stats {
    display: flex;
    justify-content: center;
    gap: 3rem;
    margin-top: 2rem;
  }

  .stat {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .stat-number {
    font-size: 2rem;
    font-weight: 700;
    color: #4F46E5;
  }

  .stat-label {
    font-size: 0.875rem;
    color: #666;
  }

  /* 团队架构 */
  .team {
    padding: 4rem 0;
    background: white;
  }

  .section-container {
    max-width: 1200px;
    margin: 0 auto;
  }

  .section-title {
    font-size: 2rem;
    font-weight: 700;
    text-align: center;
    margin-bottom: 0.5rem;
  }

  .section-subtitle {
    text-align: center;
    color: #666;
    margin-bottom: 3rem;
  }

  .team-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 2rem;
  }

  .team-card {
    background: #f8f9fa;
    border-radius: 1rem;
    padding: 2rem;
    text-align: center;
    border: 1px solid #e9ecef;
  }

  .member-avatar {
    width: 80px;
    height: 80px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 1.5rem;
    font-weight: 600;
    margin: 0 auto 1rem;
  }

  .member-name {
    font-size: 1.25rem;
    font-weight: 600;
    margin: 0 0 0.25rem;
  }

  .member-role {
    color: #4F46E5;
    font-weight: 500;
    margin-bottom: 1rem;
  }

  .member-description {
    color: #666;
    margin-bottom: 1rem;
  }

  .member-expertise {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 0.5rem;
  }

  .skill-tag {
    padding: 0.25rem 0.75rem;
    background: rgba(79, 70, 229, 0.1);
    border: 1px solid rgba(79, 70, 229, 0.2);
    border-radius: 1rem;
    font-size: 0.75rem;
    color: #4F46E5;
  }

  /* 项目展示 */
  .projects {
    padding: 4rem 0;
  }

  .projects-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    gap: 2rem;
  }

  .project-card {
    background: white;
    border-radius: 1rem;
    padding: 1.5rem;
    border: 1px solid #e9ecef;
    box-shadow: 0 2px 8px rgba(0,0,0,0.05);
  }

  .project-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 1rem;
  }

  .project-status {
    padding: 0.25rem 0.75rem;
    background: #10B981;
    color: white;
    border-radius: 1rem;
    font-size: 0.75rem;
    font-weight: 600;
  }

  .project-lead {
    font-size: 0.875rem;
    color: #666;
  }

  .project-title {
    font-size: 1.25rem;
    font-weight: 600;
    margin: 0 0 1rem;
  }

  .progress-bar {
    height: 8px;
    background: #e9ecef;
    border-radius: 4px;
    overflow: hidden;
    margin-bottom: 0.5rem;
  }

  .progress-fill {
    height: 100%;
    background: #4F46E5;
    border-radius: 4px;
  }

  .progress-text {
    font-size: 0.875rem;
    color: #666;
    text-align: right;
  }

  /* 页脚 */
  .footer {
    padding: 2rem 0;
    background: #f8f9fa;
    border-top: 1px solid #e9ecef;
  }

  .footer-container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 0 2rem;
  }

  .footer-content {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }

  .footer-logo {
    font-size: 1.25rem;
    font-weight: 700;
    color: #1a1a1a;
  }

  .footer-tagline {
    color: #666;
    font-size: 0.875rem;
  }

  .copyright {
    color: #666;
    font-size: 0.875rem;
  }

  /* 响应式设计 */
  @media (max-width: 768px) {
    .hero-title {
      font-size: 2rem;
    }
    
    .hero-stats {
      flex-direction: column;
      gap: 1.5rem;
    }
    
    .nav-menu {
      display: none;
    }
    
    .footer-content {
      flex-direction: column;
      text-align: center;
      gap: 1rem;
    }
  }
</style>
